name: image_blurhash
description: Image BlurHash
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  # blurhash_dart: ^1.1.0
  blurhash_dart: ^1.2.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  image: ^4.0.13
  # image: ^3.2.0
  tuple: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
